name: main

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [8.0, 8.1]
        os: [ubuntu-latest, macos-latest, windows-latest]
        composer: [v1, v2]
    name: PHP ${{ matrix.php }} - OS ${{ matrix.os }} - Composer ${{ matrix.composer }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
            path: |
              ~/.composer/cache/files
              ~/.composer/cache/repo
            key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: curl, zip, rar, bz2
            coverage: pcov
            tools: composer:${{ matrix.composer }}
      - name: Install unrar on Ubuntu with PHP 8.1
        run: sudo apt install unrar
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.php == '8.1' }}
      - name: Install unrar on MacOS with PHP 8.1
        run: brew install rar
        if: ${{ matrix.os == 'macos-latest' && matrix.php == '8.1' }}
      - name: Validate composer.json
        run: composer validate
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: lowest
          composer-options: "--no-progress --no-suggest"
      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --diff --dry-run
      - name: Run tests
        run: ./vendor/bin/phpunit
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v
        if: ${{ github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.composer == 'v2' && matrix.php == '8.1' }}
